/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
/* Header for class in_codekamp_opencvtest_OpencvClass */

using namespace cv;
#ifndef _Included_in_codekamp_opencvtest_OpencvClass
#define _Included_in_codekamp_opencvtest_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     in_codekamp_opencvtest_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */

 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_in_codekamp_opencvtest_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
